# Site
title:             PRO ŠESTKU 
bio:                'Jekyll version of the Massively theme by HTML5UP'
description:        "Jekyll version of the Massively theme by HTML5UP"
locale:             cs_CZ
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author: Ondřej Karas

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            default
facebook:           default
instagram:          default
github:             default

# personal
location:           Pardubice VI  
phone:              733519515 
email:              ondrej.karas@pirati.cz

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
